version: '3'

services:
  proxy:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./welcome:/usr/share/nginx/html
    networks:
      - webnet

  c2:
    build: ./ApiTester
    ports:
      - "8000:8000"
    networks:
      - webnet

  c3:
    build: ./Sintaxify
    ports:
      - "8001:8001"
    networks:
      - webnet

networks:
  webnet: