version: '3.8'
services:
  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - "8080:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2

  app1:
    build:
      context: ./app1
    container_name: app1
    ports:
      - "8000:8000"

  app2:
    build:
      context: ./app2
    container_name: app2
    ports:
      - "8001:8001"
